# Generated by Django 3.1.7 on 2021-04-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210412_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='makaleye fotoğraf ekleyin'),
        ),
    ]
